theme: jekyll-theme-clean-blog
email:              tadx.group@gmail.com
author:             F3Y & S6E
#baseurl:            "/tadx" 
url:                "https://www.tadx.fr"
repository: tadx-group/tadx.github.io

# Social Profiles
twitter_username:   TADX_Group
github_username:    tadx-group
facebook_username:  
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-156740225-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
