remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
email:              tadx.group@gmail.com
author:             F3Y & S6E
#baseurl:            "/tadx"
#url:                "https://tadx.github.io"

# Social Profiles
twitter_username:   TADX_Group
github_username:    tadx-group
facebook_username:  
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
