name: Delete env for branch

on: [delete]
    
jobs:
  delete_env:
    name: Delete env in clever for the branch
    runs-on: ubuntu-latest
    steps:
      - name: Delete bucket for branch
        run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws s3api delete-bucket --bucket ${{github.head_ref}} --endpoint-url ${{ secrets.CLEVER_END_POINT }}
