name: Jekyll site CI

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: ruby/setup-ruby@v1
      with:
    #    ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically    

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Sync output to S3
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws s3 sync ./_site/ s3://tadx-hprod --endpoint-url ${{ secrets.CLEVER_END_POINT }} --acl public-read
        
#        aws s3 ls --endpoint-url ${{ secrets.CLEVER_END_POINT }}
