name: Jekyll site CI

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    #- name: Build
     # uses: jerryjvl/jekyll-build-action@v1

    - name: Sync output to S3
      run: |
        aws s3 ls --endpoint-url ${{ secrets.CLEVER_END_POINT }}
