name: Jekyll site CI

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build
      run: |
        docker run --rm \
        --volume="$PWD:/srv/jekyll" \
        --volume="$PWD/vendor/bundle:/usr/local/bundle" \
        -it jekyll/jekyll:3.8 \
        jekyll build

#    - name: Build
#      uses: jerryjvl/jekyll-build-action@v1

    - name: Sync output to S3
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws s3 sync ./_site/ s3://tadx-hprod --endpoint-url ${{ secrets.CLEVER_END_POINT }} --acl public-read
        
#        aws s3 ls --endpoint-url ${{ secrets.CLEVER_END_POINT }}
